### ISSUE TITLE
running example 100TorrArgonPlasma/errors 

### ISSUE THREAD

**Issue by InamUlHaq4** [vayyaswamy/SOMAFOAM#10]
Hi, 

Following installation instructions (link: https://github.com/vayyaswamy/SOMAFOAM/wiki/Installation-procedure), I installed fresh ubuntu 18.04 which is although no more supported. I am successful in installing the SOMAFOAM. However, when I try to run the ''100TorrArgonPlasma'' example, it throws the errors as follows:

I run the command to clean the case: ./caseClean
output: ./caseClean: 11: ./caseClean: Syntax error: Bad for loop variable

I run the command to prepare the case: ./prepareCase
output: ./prepareCase: 8: ./prepareCase: Syntax error: Bad for loop variable

I run the command blockMesh to create mesh: blockMesh
output: Creates mesh successfully.

I run the command plasmaSimFoam to run the case: plasmaSimFoam
output: 

--> FOAM FATAL ERROR: 

    request for volVectorField gradTe from objectRegistry region0 failed
    available objects of type volVectorField are

8
(
J_electron
E
ionFlux
F_electron
J_Arp1
eeFlux
ddtE
F_Arp1
)

    From function objectRegistry::lookupObject<Type>(const word&) const
    in file /home/inam/SOMAFOAM/etc/../src/foam/lnInclude/objectRegistryTemplates.C at line 139.

FOAM aborting

snapshots are attached for reference. 

I am just trying to run the example to study the example case but I do not know how to fix the error. I tried other examples but none ran successfully but threw some errors. Can you please advise where I am making a mistake/s ? I will highly appreciate your kind response. If you have any questions or require more details, please let me know. Many thanks.

![Screenshot from 2023-09-19 14-39-39 - 1](https://github.com/vayyaswamy/SOMAFOAM/assets/92665307/2fbd1f47-6139-4efb-a14c-88b720828823)

![Screenshot from 2023-09-19 14-40-52 - 1](https://github.com/vayyaswamy/SOMAFOAM/assets/92665307/508774a4-f460-47d3-9486-6c4cbe3d755e)

![Screenshot from 2023-09-19 14-41-10](https://github.com/vayyaswamy/SOMAFOAM/assets/92665307/3f8c2be4-af76-4e91-b2cf-2b117699de0e)

**Comment by InamUlHaq4** [comment]
Hi Prof. Venkatt, thank you very much. It works this way. I have two further questions if you can kindly guide:

1. Which visualization software you recommend to use alongside SOMAFOAM ? I tried installing different versions of ParaView (newer than version 5 and older as well) but since it is Ubuntu 18.04 i.e. a Ubuntu version that is supported no more, it always throws some errors.  I also tried installing OpenFOAM 5.0, OpenFOAM 6.0, as Ubuntu 18.04 supports these OpenFOAM versions and ParaView is builtin as well in these, but it makes SOMAFOAM unable to load. If I uninstall OpenFOAM, SOMAFOAM begins to load successfully, but ParaView is also gone.  I want to visualize the results from example cases.

2. Is there a manual or a guide or a way where I can know the updated solver names such as somaFoam instead of plasmaSimFoam, since I intend to run and analyse a couple of other examples as well.

I will appreciate your kind response.

If you have any questions, please let me know.

Many thanks.

**Comment by vayyaswamy** [comment]
Dear Inam,

You could install a separate version of Paraview which is independent of OpenFOAM. OpenFOAM uses the command paraFoam to open up the results of the case in Paraview but that is not the only way. In your independently installed Paraview, you can open the .foam file of the case. It is just an empty file but can be used to open up the results.

There is no user manual at this point but the general sequence of steps to run is to do

./prepareCase
./decomposeParScript (for parallel runs)
somaFoam

Open the results in Paraview using the .foam that ./prepareCase creates automatically.

All other solvers will be deprecated and completely removed in future releases.

**Comment by InamUlHaq4** [comment]
Hi Prof. Venkatt, I hope you are well.

Thank you very much.

I can use ParaView, I understand the point was never to run update command in terminal, it causes the Ubuntu 18.04 to crash as well ParaView installation does not complete successful. 

Simply never updating the Ubuntu i.e. never executing the "sudo apt update", but instead only executing the following single command works for successful installation of ParaView (only installed operating system is Ubuntu 18.04):

"sudo apt install paraview"

It installs ParaView 5. 4. 1, but it seem not to support the functionality to support displaying dimensional units 

i.e. 

"Add dimensional units to array names", 

as whenever I check this option, ParaView crashes (snap attached).

Moreover, since I am using Ubuntu 18.04, for which official Ubuntu support has already expired, I believe SOMAFOAM yet not supported on any other/latest/supported Ubuntu version ? Please confirm.

Thank you.

Kind Regards,
Inam

![AddingDimensionaloUnits](https://github.com/vayyaswamy/SOMAFOAM/assets/92665307/b86af58d-dd5e-4b5b-9e84-a3630fee9625)
